---
# VERSION 1.0.0
- hosts: "{{ vtas_hosts }}"
  gather_facts: false
  any_errors_fatal: true
  tasks:
    - name: Facters
      veritas.infoscale.veritas_infoscale:
       module: site_facters
      register: facts
    - name: Configure SF
      veritas.infoscale.veritas_infoscale:
       module: sf_config
       license: ENTERPRISE
       product_version: 7.4.2
       seednode: objstorer820-1-vm16
       state: present
       eo_compliant_logging: off
       facters: "{{ ansible_play_hosts_all |map('extract', hostvars, \
       ['facts','infoscale_facts'])| select()|list }}"
