---
- hosts: cluster-43-44
  gather_facts: false
  any_errors_fatal: true
  tasks:
  - name: Facters
    veritas.infoscale.veritas_infoscale:
     module: site_facters
    register: facts
  - name:  Logging
    veritas.infoscale.veritas_infoscale:
      module: Logging
      state: present
      facters: "{{ ansible_play_hosts_all |map('extract', hostvars, \
      ['facts','infoscale_facts'])| select()|list }}"
