---
- hosts: mycluster
  gather_facts: False
  tasks:
    - name: Facters
      veritas.infoscale.veritas_infoscale:
        module: site_facters
      register: facts
    - name: License
      veritas.infoscale.veritas_infoscale:
        module: licensing
        state: present
        product_version: 7.4.2
        license: 'ENTERPRISE'  # or <license key file path>
        facters: "{{ ansible_play_hosts_all |map('extract', hostvars, \
        ['facts','infoscale_facts'])| select()|list }}"
